
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-test
  namespace: test
spec:
  selector:
    matchLabels:
      app: nodejs-test
  replicas: 1
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: nodejs-test
    spec:
      containers:
      - image: 406151435945.dkr.ecr.ap-south-1.amazonaws.com/nodejs-test:latest
        imagePullPolicy: Always
        name: nodejs-test
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 3
          failureThreshold: 2
        lifecycle:
          preStop:
            exec:
              command:
                - "sleep"
                - "60"
      priorityClassName: high-priority