
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-test-hpa
  namespace: test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-test
  minReplicas: 10
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60
